apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
        - name: homepage
          image: ghcr.io/gethomepage/homepage:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          envFrom:
            - secretRef:
                name: homepage-secrets
          volumeMounts:
            - name: homepage-config-homepage
              mountPath: /app/config/homepage.yaml
              subPath: homepage.yaml
            - name: homepage-config-services
              mountPath: /app/config/services.yaml
              subPath: services.yaml
            - name: homepage-config-widgets
              mountPath: /app/config/widgets.yaml
              subPath: widgets.yaml
            - name: homepage-config-bookmarks
              mountPath: /app/config/bookmarks.yaml
              subPath: bookmarks.yaml
            - name: homepage-config-settings
              mountPath: /app/config/settings.yaml
              subPath: settings.yaml
      volumes:
        - name: homepage-config-homepage
          configMap:
            name: homepage-config-homepage
        - name: homepage-config-services
          configMap:
            name: homepage-config-services
        - name: homepage-config-widgets
          configMap:
            name: homepage-config-widgets
        - name: homepage-config-bookmarks
          configMap:
            name: homepage-config-bookmarks
        - name: homepage-config-settings
          configMap:
            name: homepage-config-settings