apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wallos
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Dawo9889/homelab-2.0.git
    path: ./k3s/wallos
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: wallos
  syncPolicy:
    automated:
      enabled: true