apiVersion: v1
kind: Service
metadata:
  name: wallos
  namespace: wallos
  labels:
    app: wallos
spec:
  type: ClusterIP
  selector:
    app: wallos
  ports:
    - name: http
      port: 80
      targetPort: 80