- Applications:
    - Homepage:
        href: https://homepage.k3s.dawo9889-homelab.ovh
        description: Homepage dashboard
        icon: homepage
    - ArgoCD:
        href: https://argocd.k3s.dawo9889-homelab.ovh
        description: ArgoCD dashboard
        icon: argo-cd
    - Wallos:
        href: https://wallos.k3s.dawo9889-homelab.ovh
        description: Wallos dashboard
        icon: wallos