---
k3s_cluster:
  children:
    server:
      hosts:
        192.168.1.10:
    agent:
      hosts:
        192.168.1.11:
        192.168.1.12:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/homelab_ed25519
    ansible_ssh_common_args: -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

    k3s_version: v1.35.0+k3s1
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
