apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beszel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:Dawo9889/homelab-2.0.git
    path: ./k3s/beszel
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: beszel
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
